from datetime import date
from typing import Protocol
from uuid import UUID

from reverse_todo.domain.entities import Entry, Project, Skill, Tag, User
from reverse_todo.domain.value_objects.category import TagCategory


class UserRepository(Protocol):
    async def get_by_id(self, user_id: UUID) -> User | None: ...

    async def get_by_email(self, email: str) -> User | None: ...

    async def create(self, user: User) -> User: ...


class EntryRepository(Protocol):
    async def create(self, entry: Entry) -> Entry: ...

    async def get_by_id(self, user_id: UUID, entry_id: UUID) -> Entry | None: ...

    async def list_by_date_range(
        self, user_id: UUID, date_from: date, date_to: date
    ) -> list[Entry]: ...

    async def list_by_user(self, user_id: UUID) -> list[Entry]: ...

    async def update(self, entry: Entry) -> Entry: ...

    async def delete(self, user_id: UUID, entry_id: UUID) -> bool: ...


class TagRepository(Protocol):
    async def list_by_user(self, user_id: UUID) -> list[Tag]: ...

    async def get_or_create(
        self, user_id: UUID, name: str, category: TagCategory
    ) -> Tag: ...


class ProjectRepository(Protocol):
    async def list_by_user(self, user_id: UUID) -> list[Project]: ...

    async def get_or_create(self, user_id: UUID, name: str, color: str) -> Project: ...

    async def create(self, project: Project) -> Project: ...


class SkillRepository(Protocol):
    async def list_by_user(self, user_id: UUID) -> list[Skill]: ...

    async def get_or_create(self, user_id: UUID, name: str) -> Skill: ...
